version: '3.8'

services:
  storybook:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service for local development
  storybook-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm storybook
    environment:
      - NODE_ENV=development
    profiles:
      - dev
